In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
type(mylist)

list

In [6]:
arr = np.array(mylist)

In [7]:
arr

array([1, 2, 3])

In [8]:
mylist = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
mylist

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
mymatrix = np.array(mylist)

In [11]:
mymatrix.shape

(3, 3)

In [12]:
mynewmatrix = np.array(mylist)

In [13]:
np.arange(0.1,10,2)

array([0.1, 2.1, 4.1, 6.1, 8.1])

In [14]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
np.ones((5,5)) + 5

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [16]:
np.ones(4) / 100

array([0.01, 0.01, 0.01, 0.01])

In [17]:
np.linspace(0,10,150)

array([ 0.        ,  0.06711409,  0.13422819,  0.20134228,  0.26845638,
        0.33557047,  0.40268456,  0.46979866,  0.53691275,  0.60402685,
        0.67114094,  0.73825503,  0.80536913,  0.87248322,  0.93959732,
        1.00671141,  1.0738255 ,  1.1409396 ,  1.20805369,  1.27516779,
        1.34228188,  1.40939597,  1.47651007,  1.54362416,  1.61073826,
        1.67785235,  1.74496644,  1.81208054,  1.87919463,  1.94630872,
        2.01342282,  2.08053691,  2.14765101,  2.2147651 ,  2.28187919,
        2.34899329,  2.41610738,  2.48322148,  2.55033557,  2.61744966,
        2.68456376,  2.75167785,  2.81879195,  2.88590604,  2.95302013,
        3.02013423,  3.08724832,  3.15436242,  3.22147651,  3.2885906 ,
        3.3557047 ,  3.42281879,  3.48993289,  3.55704698,  3.62416107,
        3.69127517,  3.75838926,  3.82550336,  3.89261745,  3.95973154,
        4.02684564,  4.09395973,  4.16107383,  4.22818792,  4.29530201,
        4.36241611,  4.4295302 ,  4.4966443 ,  4.56375839,  4.63

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.random.rand(4,5)

array([[0.84312386, 0.76914973, 0.47223284, 0.51361283, 0.40385515],
       [0.72654997, 0.91918781, 0.89173326, 0.15879301, 0.39503317],
       [0.20984755, 0.96584484, 0.64449108, 0.72872758, 0.22396055],
       [0.87431794, 0.31930231, 0.61673164, 0.05831916, 0.16371569]])

In [20]:
np.random.randn(5,5)

array([[ 1.00240077,  0.08901541, -0.2913319 ,  0.72677576,  0.41420123],
       [-0.14995482, -0.43502071,  0.20147472, -1.70427197, -0.06416395],
       [ 1.04979414,  1.61157013, -0.00675548,  0.71641351, -0.81508292],
       [ 0.93662367,  1.47232889,  0.65545314,  1.80096233, -0.06307769],
       [ 0.05589365, -0.31084892, -0.53021373, -1.94205445, -0.9500041 ]])

In [21]:
np.random.normal

<function RandomState.normal>

In [22]:
np.random.randint(5,200,10)

array([ 55,  59,  20, 191, 153,  21,  65,  48, 184, 176])

In [23]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [24]:
np.random.rand(4)

array([0.68527698, 0.83389686, 0.30696622, 0.89361308])

In [25]:
np.random.rand(4)

array([0.72154386, 0.18993895, 0.55422759, 0.35213195])

In [26]:
arr = np.arange(25)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
ranarr = np.random.randint(0,50,10)

In [29]:
ranarr

array([49, 19, 47,  8, 29, 34, 44,  8, 19, 10])

In [30]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
ranarr.max()

49

In [32]:
ranarr.min()

8

In [33]:
ranarr

array([49, 19, 47,  8, 29, 34, 44,  8, 19, 10])

In [34]:
ranarr.argmax()

0

In [35]:
ranarr.argmin()

3

In [36]:
ranarr.dtype

dtype('int64')

In [37]:
arr = np.arange(0,11)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
arr[1:5]

array([1, 2, 3, 4])

In [40]:
arr[0:5]


array([0, 1, 2, 3, 4])

In [41]:
arr[:5]

array([0, 1, 2, 3, 4])

In [42]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [43]:
arr[:-5]

array([0, 1, 2, 3, 4, 5])

In [44]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [45]:
new_arr = arr / 2

In [46]:
new_arr

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [47]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [48]:
slice_of_arr = arr[0:6]

In [49]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [50]:
slice_of_arr[:] = 99

In [51]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [52]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [53]:
arr_copy = arr.copy()

In [54]:
arr_copy[:] = 10000

In [55]:
arr_copy

array([10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000,
       10000, 10000])

In [56]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [57]:
#Indezando en 2D array

In [58]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [59]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [60]:
arr_2d.shape

(3, 3)

In [61]:
arr_2d[1][1]

25

In [62]:
arr_2d[1,1]

25

In [63]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [64]:
arr = np.arange(1,11)

In [65]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
arr == 4

array([False, False, False,  True, False, False, False, False, False,
       False])

In [67]:
bool_arr = arr == 4

In [68]:
bool_arr 

array([False, False, False,  True, False, False, False, False, False,
       False])

In [69]:
arr[bool_arr]

array([4])

In [71]:
arr[arr >= 8]

array([ 8,  9, 10])